# Generated by Django 5.2.6 on 2025-09-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfctag',
            old_name='note',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='uid',
        ),
    ]
