# Generated by Django 5.2.6 on 2025-09-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_rename_note_nfctag_title_remove_nfctag_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='id',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
